apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type:  NodePort
  selector:
    tier: frontend
    app:  myapp
  ports:
  - protocol: TCP 
    port:  8080
    targetPort:  9090
    nodePort: 31000
